### ISSUE TITLE
AssertionError: can only test a child process

### ISSUE THREAD

**Issue by bwdeng20** [ashleve/lightning-hydra-template#175]
```
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fcfc2e7a5e0>
Traceback (most recent call last):
  File "/home/dbw/.conda/envs/pyg18/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/dbw/.conda/envs/pyg18/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/dbw/.conda/envs/pyg18/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

```
This seems an error arisen from `tqdm`, see this [discussion](https://discuss.pytorch.org/t/error-while-multiprocessing-in-dataloader/46845/9). However, `tqdm` used here is integrated in `pytorch_lightning`, so the workaround in that discussion is not
reachable.

**Comment by ashleve** [comment]
Thanks for reporting,
seems like it's unrelated to template thou so I believe it would be better to report it directly on pytorch lightning repo
