### ISSUE TITLE
optune gridSampler error

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#225]
In `config/hparams_search`, if I set
```
sampler:
  _target_: optuna.samplers.GridSampler
```
instead of 
```
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
     warn_independent_sampling: true
```
and run

`python run.py -m hparams_search=mnist_optuna` and error occurs.

Here is the error
```
[2021-12-14 16:01:28,584][HYDRA] Note: NumExpr detected 40 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2021-12-14 16:01:28,584][HYDRA] NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return target(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'seed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/_internal/utils.py", line 376, in <lambda>
    lambda: hydra.multirun(
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 130, in multirun
    sweeper = Plugins.instance().instantiate_sweeper(
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/core/plugins.py", line 174, in instantiate_sweeper
    sweeper = self._instantiate(config.hydra.sweeper)
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/core/plugins.py", line 93, in _instantiate
    plugin = instantiate(config=config, _target_=clazz)
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 245, in instantiate_node
    value = instantiate_node(
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(target, *args, **kwargs)
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "/home/wzhou87/miniconda3/envs/mimic_predict/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return target(*args, **kwargs)
TypeError: Error instantiating 'optuna.samplers._grid.GridSampler' : __init__() got an unexpected keyword argument 'seed'

Process finished with exit code 1
```

To the best of my effort I traced this error in to 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/28517073/146098873-026cb8db-563d-412a-a1f1-89cba4febf6a.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/28517073/146098887-0aabdc4c-6fdf-4167-8a8a-fec804db8c5f.png">

and default_list (line 250) contained a tpe sampler which has a seed

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/28517073/146098984-e3a1d7d7-d2da-4e78-972a-5a9934617f85.png">

so even though later GridSampler was used to override the tpe sampler the seed argument is still there, just set to None
<img width="434" alt="image" src="https://user-images.githubusercontent.com/28517073/146099195-2fc52661-9fa5-467b-bec7-c7e76446fca7.png">
<img width="871" alt="image" src="https://user-images.githubusercontent.com/28517073/146099206-b1535121-4c81-42de-851a-cdc03ac16a7b.png">

<img width="961" alt="image" src="https://user-images.githubusercontent.com/28517073/146099064-59279bbc-829f-4765-b859-25be2e8be8f9.png">

This is just my guess and it is difficult for me to go further.

Also if you remove the `-m` and only run `python run.py hparams_search=mnist_optuna`, this error no longer appears.

My guess is the multirun sets a default tpe sampler for hyparam sarch while single run does not. So there is no error.

**Comment by ashleve** [comment]
Take a look at [this discussion](https://github.com/ashleve/lightning-hydra-template/discussions/171).

It seems like GridSampler is not supported by the plugin

**Comment by dreaquil** [comment]
To use grid sampler, you can add the following line at the top of your `hparams_search` config in the defaults section:
`- override /hydra/sweeper/sampler: grid`

![image](https://github.com/ashleve/lightning-hydra-template/assets/32460579/e0633e5a-f187-4ef0-913e-4360b5d67af3)
