### ISSUE TITLE
hydra-optuna-sweeper and wandb versions conflict

### ISSUE THREAD

**Issue by GillianGrayson** [ashleve/lightning-hydra-template#362]
Hi!

I have installed all required packages by `pip install -r requrements.txt` and tried to run hyperparametric search using the [file](https://github.com/ashleve/lightning-hydra-template/blob/main/configs/hparams_search/mnist_optuna.yaml):
```
train.py -m hparams_search=mnist_optuna experiment=example
``` 
I faced 2 problems:

# 1. hydra-optuna-sweeper problem

I got the following error:
```
Traceback (most recent call last):
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\hydra\_internal\utils.py", line 213, in run_and_report
    return func()
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\hydra\_internal\utils.py", line 461, in <lambda>
    lambda: hydra.multirun(
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\hydra\_internal\hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\hydra_plugins\hydra_optuna_sweeper\optuna_sweeper.py", line 52, in sweep
    return self.sweeper.sweep(arguments)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\hydra_plugins\hydra_optuna_sweeper\_impl.py", line 289, in sweep
    assert self.search_space is None
AssertionError
```
The same error was reported in [this issue](https://github.com/facebookresearch/hydra/issues/2253).

File [requrements.txt](https://github.com/ashleve/lightning-hydra-template/blob/main/requirements.txt) contains the following versions for hydra-optuna-sweeper:
```
# --------- hydra --------- #
hydra-core>=1.1.0
hydra-colorlog>=1.1.0
hydra-optuna-sweeper>=1.1.0
```
But the latest versions of the packages are installing:
```
hydra-colorlog==1.2.0
hydra-core==1.2.0
hydra-optuna-sweeper==1.2.0
```

If I understand correctly, optuna sweeper's syntax has changed in hydra since version 1.2.0. When I change the syntax to the new version (as it was in mentioned above [issue](https://github.com/facebookresearch/hydra/issues/2253)):
```yaml
hydra:
  sweeper:
    ...
    params:
      datamodule.batch_size: choice(32,64,128)
      model.lr: interval(0.0001, 0.2)
      model.net.lin1_size: choice(32, 64, 128, 256, 512)
      model.net.lin2_size: choice(32, 64, 128, 256, 512)
      model.net.lin3_size: choice(32, 64, 128, 256, 512)
```
everything works without errors.

# 2. wandb problem
After the command `pip install -r requrements.txt` wandb==0.12.20 was installed.
When running the training process with this logger:
```
train.py -m hparams_search=mnist_optuna experiment=example logger=wandb
```
The first run with the certian parameters combination finished successfully, the second run had the error:

```
Exception in thread StreamThr:
Traceback (most recent call last):
  File "C:\Users\yusip\anaconda3\envs\py39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\service\streams.py", line 40, in run
    self._target(**self._kwargs)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\internal\internal.py", line 85, in wandb_internal
    configure_logging(_settings.log_internal, _settings._log_level)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\internal\internal.py", line 189, in configure_logging
    log_handler = logging.FileHandler(log_fname)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\logging\__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\yusip\anaconda3\envs\py39\lib\logging\__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yusip\\Desktop\\lightning-hydra-template-main\\logs\\experiments\\multiruns\\simple_dense_net\\2022-06-30_14-36-03\\0\\wandb\\run-2022
0630_143648-2vxuij78\\logs\\debug-internal.log'
Traceback (most recent call last):
  File "C:\Users\yusip\anaconda3\envs\py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yusip\anaconda3\envs\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\cli\cli.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\cli\cli.py", line 285, in service
    server.serve()
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\service\server.py", line 140, in serve
    mux.loop()
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\service\streams.py", line 332, in loop
    raise e
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\service\streams.py", line 330, in loop
    self._loop()
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\service\streams.py", line 323, in _loop
    self._process_action(action)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\service\streams.py", line 288, in _process_action
    self._process_add(action)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\service\streams.py", line 208, in _process_add
    stream.start_thread(thread)
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\service\streams.py", line 68, in start_thread
    self._wait_thread_active()
  File "C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\wandb\sdk\service\streams.py", line 73, in _wait_thread_active
    assert result
AssertionError
Problem at: C:\Users\yusip\anaconda3\envs\py39\lib\site-packages\pytorch_lightning\loggers\wandb.py 357 experiment
wandb: ERROR Error communicating with wandb process
wandb: ERROR try: wandb.init(settings=wandb.Settings(start_method='fork'))
wandb: ERROR or:  wandb.init(settings=wandb.Settings(start_method='thread'))
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
Error executing job with overrides: ['datamodule.batch_size=32', 'model.lr=0.09357304154313738', 'model.net.lin1_size=256', 'model.net.lin2_size=512', 'model.net.lin3_size=256', 'hparams_search=mnist_op
tuna', 'experiment=example', 'logger=wandb']
Error in call to target 'pytorch_lightning.loggers.wandb.WandbLogger':
UsageError("Error communicating with wandb process\ntry: wandb.init(settings=wandb.Settings(start_method='fork'))\nor:  wandb.init(settings=wandb.Settings(start_method='thread'))\nFor more info see: htt
ps://docs.wandb.ai/library/init#init-start-error")
full_key: logger.wandb
```
It is not clear, which parameters should be passed to pytorch lighting wrapper when initializinig this logger, to avoid this error.

**Comment by yipliu** [comment]
Hi @GillianGrayson 

For **1. hydra-optuna-sweeper problem**, it has been modified in release_1.4. You can find [here](https://github.com/ashleve/lightning-hydra-template/blob/7e67c4692590550e7b703655845e59508eb071bb/configs/hparams_search/mnist_optuna.yaml#L49)

**Comment by ashleve** [comment]
@GillianGrayson ty for reporting, the problems no longer exist on the current `main` branch as far as I'm aware.
