### ISSUE TITLE
rename task_name failed

### ISSUE THREAD

**Issue by YChienHung** [ashleve/lightning-hydra-template#644]
When I run command 
**python src/train.py trainer=ddp logger=csv model=mnist data=mnist callbacks=default task_name="new_task_name"**,

An error occurred
Traceback (most recent call last):
  File "/root/data/---/project/---/src/train.py", line 132, in <module>
    main()
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
          ^^^^^^^^^^^^^^^^^^^^
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/config_loader_impl.py", line 244, in _load_configuration_impl
    parsed_overrides, caching_repo = self._parse_overrides_and_create_caching_repo(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/_internal/config_loader_impl.py", line 228, in _parse_overrides_and_create_caching_repo
    parsed_overrides = parser.parse_overrides(overrides=overrides)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/data/anaconda3/envs/---/lib/python3.11/site-packages/hydra/core/override_parser/overrides_parser.py", line 96, in parse_overrides
    raise OverrideParseException(
hydra.errors.OverrideParseException: LexerNoViableAltException: task_name=new_task_name
                                                      ^
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details

**Comment by YChienHung** [comment]
amazing, the command runs without error
**python src/train.py trainer=ddp logger=csv model=mnist data=mnist callbacks=default task_name="new_task_name" # abc**
